excluded:
    - Pods
    - Carthage
disabled_rules:
    - identifier_name
    - function_parameter_count
    - force_cast
    - trailing_comma
    - function_body_length
    - cyclomatic_complexity
    - file_length
    - type_body_length
    - opening_brace
line_length: 160
type_name:
  max_length: 60
nesting:
    type_level: 3