objc: true
clean: true
sdk: iphonesimulator

theme: ../../Themes/apple

module: AppCenterAnalytics
module_version: 3.3.2
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Analytics.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/iOS/AppCenterAnalytics.framework/Headers/AppCenterAnalytics.h
framework_root: ../../../AppCenter-SDK-Apple/iOS/
exclude: [../../../AppCenter-SDK-Apple/iOS/AppCenterAnalytics.framework/Headers/MSService.h, ../../../AppCenter-SDK-Apple/iOS/AppCenterAnalytics.framework/Headers/MSServiceAbstract.h]

root_url: https://docs.microsoft.com/appcenter/sdk/ios
github_url: https://github.com/microsoft/appcenter-sdk-apple
github_file_prefix: "https://github.com/microsoft/appcenter-sdk-apple"

skip_undocumented: true

output: Generated/
